name: CI workflow

on: [push]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set "In Progress" check
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Server Tests
          status: in_progress
          output: |
            {"summary":"In Progress"}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install --dev

      - name: Server tests
        env: 
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm test

      - name: Success
        uses: LouisBrunner/checks-action@v1.1.1
        if: ${{ success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Server Tests
          status: completed
          conclusion: success
          output: |
            {"summary":"Success"}

      - name: Failure
        uses: LouisBrunner/checks-action@v1.1.1
        if: ${{ failure() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Server Tests
          status: completed
          conclusion: failure
          output: |
            {"summary":"Failed"}